# Vagrantfile

Vagrant.configure(2) do |config|

    # ==> Choose a Vagrant box to emulate Linux distribution...
    #config.vm.box = "ubuntu/trusty64"
    #config.vm.box = "ubuntu/precise64"
    #config.vm.box = "debian/jessie64"
    config.vm.box = "debian/wheezy64"
    #config.vm.box = "bento/centos-7.1"
    #config.vm.box = "bento/centos-6.7"
    #config.vm.box = "maier/alpine-3.1.3-x86_64"

    # ==> Executing Ansible...
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end

end
